#!/bin/bash

# USAGE:
# $ whisk new "Lorem ipsum."
# $ whisk make
# $ whisk view


#-- Ask the user what to name the thing
#   if the user has not specified.
getName () {
    if [[ -z "$1" ]]; then
        read -e -p "Name for new note: " NAME
    else
        NAME="$1"
    fi
    echo "$NAME"
}

#-- Abort with a message
abort_and_reopen () {
    echo "File $1 already exists."
    open -n "$1"
    exit 1
}

#-- Trim whitespace and hyphens
trim() {
    local var="$*"
    var="${var#"${var%%[![:space:]-]*}"}"   # remove leading whitespace characters
    var="${var%"${var##*[![:space:]-]}"}"   # remove trailing whitespace characters
    echo -n "$var"
}

case "$1" in
#-- New note in current directory (no overwrite)
new)
    TITLE=$(getName "$2")
    SLUG="$(echo -n ${TITLE} | sed -e 's/[^[:alnum:]]/-/g' \
                | tr -s '-' | tr A-Z a-z)"
    SLUG=$(trim $SLUG)
    DATE=$(date +"%Y-%m-%d")
    FILE="$DATE-$SLUG".markdown

    # No overwrite.
    [[ -f $FILE ]] && $(abort_and_reopen "$FILE")

    AUTHOR=""
    DATE=$(date +"%a %d %b %Y")
    echo -e $"title:  $TITLE\nauthor: ${AUTHOR}\ndate:   $DATE\ntags:   \n" > $FILE
    open -n "$FILE"
    ;;

# # Whisk make.
# make)
#     pushd "$WHISK_DIR" > /dev/null
#     python "$WHISK_DIR/whisk.py"
#     popd > /dev/null
#     ;;

#-- Whisk open.
view)
    open "index.html"
    ;;

esac
