#!/bin/bash

# USAGE:
#   $ note "Title of note."

# Set the author here. In the future the author should be
# able to be set by a flag.
AUTHOR="Hrothgar"

# By default, notes go the working directory.
NOTES_DIR="."

#-- Ask the user what to name the thing
#   if the user has not specified.
getName () {
    if [[ -z "$1" ]]; then
        read -e -p "Name for new note: " NAME
    else
        NAME="$1"
    fi
    echo "$NAME"
}

#-- Abort with a message
abort_and_reopen () {
    echo "File $1 already exists."
    subl -n "$1"
    exit 1
}

#-- Trim whitespace and hyphens
trim() {
    local var="$*"
    var="${var#"${var%%[![:space:]-]*}"}"   # remove leading whitespace characters
    var="${var%"${var##*[![:space:]-]}"}"   # remove trailing whitespace characters
    echo -n "$var"
}


TITLE=$(getName "$1")
SLUG="$(echo -n ${TITLE} | sed -e 's/[^[:alnum:]]/-/g' \
            | tr -s '-' | tr A-Z a-z)"
SLUG=$(trim $SLUG)
DATE=$(date +"%Y-%m-%d")
FILE="$NOTES_DIR/$DATE-$SLUG".markdown

# No overwrite.
[[ -f $FILE ]] && $(abort_and_reopen "$FILE")

DATE=$(date +"%a %d %b %Y")
echo -e $"title:  $TITLE\nauthor: ${AUTHOR}\ndate:   $DATE\n" > $FILE
subl -n "$FILE"
