#!/bin/bash

# USAGE:
# $ whisk -n "Lorem ipsum."
# $ whisk make
# $ whisk view

WHISK_DIR="/Users/hrothgar/Desktop/whisk"

#-- Ask the user what to name the thing
#   if the user has not specified.
getName () {
    if [[ -z "$1" ]]; then
        read -e -p "Name for new note: " NAME
    else
        NAME="$1"
    fi
    echo "$NAME"
}

#-- Abort with a message
abort_and_reopen () {
    echo "File $1 already exists."
    subl -n "$1"
    exit 1
}

#-- Trim whitespace and hyphens
trim() {
    local var="$*"
    var="${var#"${var%%[![:space:]-]*}"}"   # remove leading whitespace characters
    var="${var%"${var##*[![:space:]-]}"}"   # remove trailing whitespace characters
    echo -n "$var"
}

case "$1" in
#-- New note in current directory (no overwrite)
-n)
    TITLE=$(getName "$2")
    SLUG="$(echo -n ${TITLE} | sed -e 's/[^[:alnum:]]/-/g' \
                | tr -s '-' | tr A-Z a-z)"
    SLUG=$(trim $SLUG)
    DATE=$(date +"%Y-%m-%d")
    FILE="$WHISK_DIR/$DATE-$SLUG".markdown

    # No overwrite.
    [[ -f $FILE ]] && $(abort_and_reopen "$FILE")

    AUTHOR="Hrothgar"
    DATE=$(date +"%a %d %b %Y")
    echo -e $"title:  $TITLE\nauthor: ${AUTHOR}\ndate:   $DATE\ntags:   \n" > $FILE
    subl -n "$FILE"
    ;;

# Whisk make.
make)
    pushd "$WHISK_DIR" > /dev/null
    python "$WHISK_DIR/whisk.py"
    popd > /dev/null
    ;;

#-- Whisk open.
view)
    open "$WHISK_DIR/index.html"
    ;;

esac
